# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # Specify the package manager
    directory: '/' # Location of the `package.json` file
    schedule:
      interval: 'monthly' # Frequency of update checks
    commit-message:
      prefix: 'chore(deps)' # Prefix for Dependabot commit messages
    labels:
      - 'dependencies' # Label to categorize pull requests
    open-pull-requests-limit: 10 # Increased limit for open Dependabot PRs
    versioning-strategy: 'auto' # Options: auto, widen, lockfile-only
    rebase-strategy: 'auto' # Rebase only when necessary
