frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/**'
          - 'src/app/**'
          - 'src/hooks/**'
          - 'src/context/**'
          - 'src/lib/**'
          - 'src/services/**'
          - 'src/types/**'

ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/ui/**'

data:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/data/**'

config:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/config/**'
          - 'next.config.js'
          - 'tsconfig.json'
          - 'eslint.config.mjs'
          - 'postcss.config.mjs'
          - 'prettier.config.cjs'
          - 'components.json'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'
          - 'LICENSE*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'

assets:
  - changed-files:
      - any-glob-to-any-file:
          - 'public/**'

api:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/api/**'
