changelog:
  exclude:
    labels:
      - 'dependencies'
  categories:
    - title: 'New Features'
      labels:
        - 'frontend'
        - 'enhancement'
    - title: 'Bug Fixes'
      labels:
        - 'bug'
    - title: 'Documentation'
      labels:
        - 'docs'
    - title: 'CI/CD'
      labels:
        - 'ci'
    - title: 'Other Changes'
      labels:
        - '*'
