import type { Metadata, Viewport } from 'next';
import { Inter, Playfair_Display, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout-content/header';
import Footer from '@/components/layout-content/footer';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';
import { Providers } from '@/components/providers/providers';
import { JsonLd } from '@/components/seo/json-ld';
import { ScrollToTop } from '@/components/scroll-to-top';
import { CommandMenu } from '@/components/command-menu';
import { siteConfig } from '@/config/site';
import { env } from '@/env';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const fontSerif = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif',
  display: 'swap',
});

const fontMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.title,
    template: siteConfig.titleTemplate,
  },
  description: siteConfig.description,
  keywords: [...siteConfig.keywords],
  authors: [{ name: siteConfig.author.name, url: siteConfig.url }],
  creator: siteConfig.author.name,
  // OG / Twitter images are generated by `opengraph-image.tsx` + `twitter-image.tsx`
  // and auto-attached by Next.js — no `images` array needed here.
  openGraph: {
    type: 'website',
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: `${siteConfig.author.name}'s Portfolio`,
    title: siteConfig.title,
    description: siteConfig.shortDescription,
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.title,
    description: siteConfig.shortDescription,
    creator: siteConfig.author.twitterHandle,
  },
  appleWebApp: {
    capable: true,
    title: siteConfig.author.name,
    statusBarStyle: 'black-translucent',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: env.GOOGLE_VERIFICATION_CODE,
  },
  alternates: {
    canonical: siteConfig.url,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ECE6D6' },
    { media: '(prefers-color-scheme: dark)', color: '#1A1714' },
  ],
  colorScheme: 'light dark',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={siteConfig.language} suppressHydrationWarning>
      <head>
        <JsonLd />
      </head>
      <body
        suppressHydrationWarning
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} flex min-h-screen flex-col font-sans antialiased`}
      >
        {/* A11y: bypasses nav for keyboard / screen-reader users.
            Hidden visually until focused — at which point it animates
            into the top-left corner with a focus ring. */}
        <a
          href="#main"
          className="sr-only focus-visible:not-sr-only focus-visible:fixed focus-visible:left-4 focus-visible:top-4 focus-visible:z-100 focus-visible:rounded-md focus-visible:border focus-visible:bg-background focus-visible:px-4 focus-visible:py-2 focus-visible:text-sm focus-visible:font-medium focus-visible:text-foreground focus-visible:shadow-md focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
        >
          Skip to content
        </a>
        <Providers>
          <Header />
          <main
            id="main"
            className="grow mx-auto w-full max-w-3xl px-8 pt-8 pb-16"
          >
            {children}
            <Analytics />
            <SpeedInsights />
          </main>
          <Footer />
          <ScrollToTop />
          <CommandMenu />
        </Providers>
      </body>
    </html>
  );
}
