import type { Metadata, Viewport } from 'next';
import { Suspense } from 'react';
import { Inter, Playfair_Display, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout-content/header';
import Footer from '@/components/layout-content/footer';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';
import { Providers } from '@/components/providers/providers';
import { JsonLd } from '@/components/seo/json-ld';
import { ScrollToTop } from '@/components/scroll-to-top';
import { CommandMenu } from '@/components/command-menu';
import { AssistantModal } from '@/components/assistant-ui/assistant-modal';
import { ChatRuntimeProvider } from '@/components/chat/chat-runtime-provider';
import { siteConfig } from '@/config/site';
import { env } from '@/env';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const fontSerif = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif',
  display: 'swap',
});

const fontMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.title,
    template: siteConfig.titleTemplate,
  },
  description: siteConfig.description,
  keywords: [...siteConfig.keywords],
  authors: [{ name: siteConfig.author.name, url: siteConfig.url }],
  creator: siteConfig.author.name,
  // OG / Twitter images are generated by `opengraph-image.tsx` + `twitter-image.tsx`
  // and auto-attached by Next.js — no `images` array needed here.
  openGraph: {
    type: 'website',
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: `${siteConfig.author.name}'s Portfolio`,
    title: siteConfig.title,
    description: siteConfig.shortDescription,
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.title,
    description: siteConfig.shortDescription,
    creator: siteConfig.author.twitterHandle,
  },
  appleWebApp: {
    capable: true,
    title: siteConfig.author.name,
    statusBarStyle: 'black-translucent',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: env.GOOGLE_VERIFICATION_CODE,
  },
  alternates: {
    canonical: siteConfig.url,
    // RSS autodiscovery — feed readers (and dev.to's "publish via RSS"
    // setup form) look for this `<link rel="alternate">` tag to find
    // the feed URL automatically. Live route at `src/app/feed.xml/`.
    types: {
      'application/rss+xml': '/feed.xml',
    },
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ECE6D6' },
    { media: '(prefers-color-scheme: dark)', color: '#1A1714' },
  ],
  colorScheme: 'light dark',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang={siteConfig.language}
      suppressHydrationWarning
      // `scroll-smooth` enables CSS-driven smooth scrolling for in-page
      // anchor jumps (e.g. the home-page section rail's `<a href="#id">`
      // clicks). The reduced-motion media query in `globals.css` overrides
      // back to `auto` for users who prefer reduced motion.
      //
      // `data-scroll-behavior="smooth"` is Next 16's opt-in signal that
      // we *intentionally* set `scroll-behavior: smooth` — without it,
      // the router also tries to smooth-animate route transitions on
      // top, which feels laggy. Docs:
      // https://nextjs.org/docs/messages/missing-data-scroll-behavior
      className="scroll-smooth"
      data-scroll-behavior="smooth"
    >
      <head>
        <JsonLd />
      </head>
      <body
        suppressHydrationWarning
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} flex min-h-screen flex-col font-sans antialiased`}
      >
        {/* A11y: bypasses nav for keyboard / screen-reader users.
            Hidden visually until focused — at which point it animates
            into the top-left corner with a focus ring. */}
        <a
          href="#main"
          className="sr-only focus-visible:not-sr-only focus-visible:fixed focus-visible:left-4 focus-visible:top-4 focus-visible:z-100 focus-visible:rounded-md focus-visible:border focus-visible:bg-background focus-visible:px-4 focus-visible:py-2 focus-visible:text-sm focus-visible:font-medium focus-visible:text-foreground focus-visible:shadow-md focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
        >
          Skip to content
        </a>
        <Providers>
          <Header />
          <main
            id="main"
            className="grow mx-auto w-full max-w-3xl px-8 pt-8 pb-16"
          >
            {children}
            <Analytics />
            <SpeedInsights />
          </main>
          <Footer />
          <ScrollToTop />
          <CommandMenu />
          {/* Suspense + ChatRuntimeProvider together: assistant-ui's
              `useChatRuntime` calls `Math.random()` at hook-init time,
              which Next 16's `cacheComponents` mode flags during
              prerender. Deferring this subtree to client hydration with
              a null fallback removes the warning at zero LCP cost — the
              floating modal isn't LCP content. Documented Next 16
              pattern, not a workaround. */}
          <Suspense fallback={null}>
            <ChatRuntimeProvider>
              <AssistantModal />
            </ChatRuntimeProvider>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
